<?php

namespace Database\Seeders;

use App\Models\Twenty\City;
use App\Models\Twenty\Governorate;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    public function run(): void
    {
        $citiesMap = [
            'القاهرة' => [
                ['ar' => 'مدينة نصر', 'en' => 'Nasr City'],
                ['ar' => 'مصر الجديدة', 'en' => 'Heliopolis'],
                ['ar' => 'المعادي', 'en' => 'Maadi'],
                ['ar' => 'التجمع الخامس', 'en' => 'Fifth Settlement'],
                ['ar' => 'التجمع الأول', 'en' => 'First Settlement'],
                ['ar' => 'التجمع الثالث', 'en' => 'Third Settlement'],
                ['ar' => 'الرحاب', 'en' => 'Al Rehab'],
                ['ar' => 'مدينتي', 'en' => 'Madinaty'],
                ['ar' => 'الشروق', 'en' => 'Al Shorouk'],
                ['ar' => 'بدر', 'en' => 'Badr City'],
                ['ar' => 'العاصمة الإدارية الجديدة', 'en' => 'New Administrative Capital'],
                ['ar' => 'المستقبل', 'en' => 'Al Mostaqbal City'],
                ['ar' => 'حلوان', 'en' => 'Helwan'],
                ['ar' => 'المعصرة', 'en' => 'Al Maasara'],
                ['ar' => '15 مايو', 'en' => '15th of May City'],
                ['ar' => 'الزمالك', 'en' => 'Zamalek'],
                ['ar' => 'جاردن سيتي', 'en' => 'Garden City'],
                ['ar' => 'وسط البلد', 'en' => 'Downtown Cairo'],
                ['ar' => 'المنيل', 'en' => 'Al Manyal'],
                ['ar' => 'شبرا', 'en' => 'Shubra'],
                ['ar' => 'الزيتون', 'en' => 'Al Zaytoun'],
                ['ar' => 'المطرية', 'en' => 'Al Matariyyah'],
                ['ar' => 'عين شمس', 'en' => 'Ain Shams'],
                ['ar' => 'المرج', 'en' => 'Al Marg'],
                ['ar' => 'النزهة', 'en' => 'Al Nozha'],
                ['ar' => 'الوايلي', 'en' => 'Al Wayli'],
                ['ar' => 'العباسية', 'en' => 'Abbassia'],
                ['ar' => 'باب الشعرية', 'en' => 'Bab Al Shariya'],
                ['ar' => 'الموسكي', 'en' => 'Al Mosky'],
                ['ar' => 'عابدين', 'en' => 'Abdeen'],
                ['ar' => 'السيدة زينب', 'en' => 'Sayeda Zeinab'],
                ['ar' => 'الخليفة', 'en' => 'Al Khalifa'],
                ['ar' => 'المقطم', 'en' => 'Al Mokattam'],
                ['ar' => 'مصر القديمة', 'en' => 'Old Cairo'],
                ['ar' => 'دار السلام', 'en' => 'Dar Al Salam'],
                ['ar' => 'البساتين', 'en' => 'Al Basateen'],
                ['ar' => 'روض الفرج', 'en' => 'Rod El Farag'],
                ['ar' => 'الساحل', 'en' => 'Al Sahel'],
                ['ar' => 'الأزبكية', 'en' => 'Al Azbakeya'],
                ['ar' => 'بولاق', 'en' => 'Boulaq'],
            ],
            'الجيزة' => [
                ['ar' => 'الدقي', 'en' => 'Dokki'],
                ['ar' => 'المهندسين', 'en' => 'Mohandessin'],
                ['ar' => 'العجوزة', 'en' => 'Agouza'],
                ['ar' => 'حي الجيزة', 'en' => 'Giza District'],
                ['ar' => 'الهرم', 'en' => 'Haram'],
                ['ar' => 'فيصل', 'en' => 'Faisal'],
                ['ar' => 'العمرانية', 'en' => 'Omraneya'],
                ['ar' => 'بولاق الدكرور', 'en' => 'Boulaq Al Dakrour'],
                ['ar' => 'الوراق', 'en' => 'Al Warraq'],
                ['ar' => 'إمبابة', 'en' => 'Imbaba'],
                ['ar' => 'كرداسة', 'en' => 'Kerdasa'],
                ['ar' => 'أوسيم', 'en' => 'Ausim'],
                ['ar' => 'منشأة القناطر', 'en' => 'Manshiyat Al Qanater'],
                ['ar' => 'مدينة 6 أكتوبر', 'en' => '6th of October'],
                ['ar' => 'الشيخ زايد', 'en' => 'Sheikh Zayed'],
                ['ar' => 'أكتوبر الجديدة', 'en' => 'New October'],
                ['ar' => 'حدائق أكتوبر', 'en' => 'October Gardens'],
                ['ar' => 'الحوامدية', 'en' => 'Al Hawamdiya'],
                ['ar' => 'البدرشين', 'en' => 'Al Badrashein'],
                ['ar' => 'العياط', 'en' => 'Al Ayat'],
                ['ar' => 'الصف', 'en' => 'Al Saff'],
                ['ar' => 'أطفيح', 'en' => 'Atfeeh'],
                ['ar' => 'الواحات البحرية', 'en' => 'Bahariya Oasis'],
                ['ar' => 'أبو النمرس', 'en' => 'Abu El Nomros'],
            ],
            'الإسكندرية' => [
                ['ar' => 'سموحة', 'en' => 'Smouha'],
                ['ar' => 'سيدي جابر', 'en' => 'Sidi Gaber'],
                ['ar' => 'سيدي بشر', 'en' => 'Sidi Bishr'],
                ['ar' => 'ميامي', 'en' => 'Miami'],
                ['ar' => 'المنتزه', 'en' => 'Al Montazah'],
                ['ar' => 'العصافرة', 'en' => 'Al Asafra'],
                ['ar' => 'المندرة', 'en' => 'Al Mandara'],
                ['ar' => 'المعمورة', 'en' => 'Al Mamoura'],
                ['ar' => 'أبو قير', 'en' => 'Abu Qir'],
                ['ar' => 'لوران', 'en' => 'Loran'],
                ['ar' => 'جليم', 'en' => 'Glim'],
                ['ar' => 'جناكليس', 'en' => 'Gnaklis'],
                ['ar' => 'سبورتنج', 'en' => 'Sporting'],
                ['ar' => 'كليوباترا', 'en' => 'Cleopatra'],
                ['ar' => 'الإبراهيمية', 'en' => 'Al Ibrahimeya'],
                ['ar' => 'الشاطبي', 'en' => 'Al Shatby'],
                ['ar' => 'محطة الرمل', 'en' => 'Raml Station'],
                ['ar' => 'كوم الدكة', 'en' => 'Kom El Dekka'],
                ['ar' => 'كرموز', 'en' => 'Karmouz'],
                ['ar' => 'محرم بك', 'en' => 'Moharam Bek'],
                ['ar' => 'مينا البصل', 'en' => 'Mina El Basal'],
                ['ar' => 'اللبان', 'en' => 'Al Labban'],
                ['ar' => 'المنشية', 'en' => 'Al Mansheya'],
                ['ar' => 'الجمرك', 'en' => 'Al Gomrok'],
                ['ar' => 'بحري', 'en' => 'Bahary'],
                ['ar' => 'الدخيلة', 'en' => 'Al Dekheila'],
                ['ar' => 'المكس', 'en' => 'Al Max'],
                ['ar' => 'العجمي', 'en' => 'Al Agami'],
                ['ar' => 'الهانوفيل', 'en' => 'Hanoville'],
                ['ar' => 'البيطاش', 'en' => 'Bitash'],
                ['ar' => 'العامرية', 'en' => 'Al Amriya'],
                ['ar' => 'كينج مريوط', 'en' => 'King Mariout'],
                ['ar' => 'برج العرب', 'en' => 'Borg El Arab'],
                ['ar' => 'برج العرب الجديدة', 'en' => 'New Borg El Arab'],
            ],
            'القليوبية' => [
                ['ar' => 'بنها', 'en' => 'Banha'],
                ['ar' => 'شبرا الخيمة', 'en' => 'Shubra El Kheima'],
                ['ar' => 'قليوب', 'en' => 'Qalyub'],
                ['ar' => 'القناطر الخيرية', 'en' => 'Al Qanater Al Khayriyyah'],
                ['ar' => 'الخانكة', 'en' => 'Al Khanka'],
                ['ar' => 'كفر شكر', 'en' => 'Kafr Shukr'],
                ['ar' => 'طوخ', 'en' => 'Toukh'],
                ['ar' => 'قها', 'en' => 'Qaha'],
                ['ar' => 'شبين القناطر', 'en' => 'Shibin Al Qanater'],
                ['ar' => 'الخصوص', 'en' => 'Al Khusus'],
                ['ar' => 'العبور', 'en' => 'Al Obour'],
                ['ar' => 'العبور الجديدة', 'en' => 'New Obour'],
            ],
            'الدقهلية' => [
                ['ar' => 'المنصورة', 'en' => 'Mansoura'],
                ['ar' => 'المنصورة الجديدة', 'en' => 'New Mansoura'],
                ['ar' => 'ميت غمر', 'en' => 'Mit Ghamr'],
                ['ar' => 'السنبلاوين', 'en' => 'El Senbellawein'],
                ['ar' => 'دكرنس', 'en' => 'Dikirnis'],
                ['ar' => 'طلخا', 'en' => 'Talkha'],
                ['ar' => 'بلقاس', 'en' => 'Belqas'],
                ['ar' => 'أجا', 'en' => 'Aga'],
                ['ar' => 'شربين', 'en' => 'Sherbin'],
                ['ar' => 'تمي الأمديد', 'en' => 'Timay El Amdid'],
                ['ar' => 'بني عبيد', 'en' => 'Bani Ubaid'],
                ['ar' => 'ميت سلسيل', 'en' => 'Mit Salsil'],
                ['ar' => 'المنزلة', 'en' => 'Al Manzala'],
                ['ar' => 'الجمالية', 'en' => 'Al Gamaliya'],
                ['ar' => 'منية النصر', 'en' => 'Minyat Al Nasr'],
                ['ar' => 'نبروه', 'en' => 'Nabaroh'],
                ['ar' => 'محلة دمنة', 'en' => 'Mahallat Damana'],
                ['ar' => 'جمصة', 'en' => 'Gamasa'],
            ],
            'الشرقية' => [
                ['ar' => 'الزقازيق', 'en' => 'Zagazig'],
                ['ar' => 'العاشر من رمضان', 'en' => '10th of Ramadan'],
                ['ar' => 'بلبيس', 'en' => 'Belbeis'],
                ['ar' => 'منيا القمح', 'en' => 'Minya El Qamh'],
                ['ar' => 'فاقوس', 'en' => 'Faqous'],
                ['ar' => 'أبو حماد', 'en' => 'Abu Hammad'],
                ['ar' => 'ههيا', 'en' => 'Hihya'],
                ['ar' => 'كفر صقر', 'en' => 'Kafr Saqr'],
                ['ar' => 'أولاد صقر', 'en' => 'Awlad Saqr'],
                ['ar' => 'الإبراهيمية', 'en' => 'Al Ibrahimiya'],
                ['ar' => 'ديرب نجم', 'en' => 'Deyrb Negm'],
                ['ar' => 'مشتول السوق', 'en' => 'Mashtool El Souk'],
                ['ar' => 'الصالحية الجديدة', 'en' => 'New Salhiya'],
                ['ar' => 'الحسينية', 'en' => 'Al Husseiniya'],
                ['ar' => 'أبو كبير', 'en' => 'Abu Kabir'],
                ['ar' => 'القرين', 'en' => 'Al Qurein'],
                ['ar' => 'القنايات', 'en' => 'Al Qanayat'],
                ['ar' => 'صان الحجر', 'en' => 'San El Hagar'],
            ],
            'المنوفية' => [
                ['ar' => 'شبين الكوم', 'en' => 'Shibin El Kom'],
                ['ar' => 'منوف', 'en' => 'Menouf'],
                ['ar' => 'أشمون', 'en' => 'Ashmoun'],
                ['ar' => 'مدينة السادات', 'en' => 'Sadat City'],
                ['ar' => 'قويسنا', 'en' => 'Quesna'],
                ['ar' => 'بركة السبع', 'en' => 'Barkat El Sabaa'],
                ['ar' => 'تلا', 'en' => 'Tala'],
                ['ar' => 'الشهداء', 'en' => 'Al Shohada'],
                ['ar' => 'الباجور', 'en' => 'Al Bagour'],
                ['ar' => 'سرس الليان', 'en' => 'Sers El Lyan'],
            ],
            'الغربية' => [
                ['ar' => 'طنطا', 'en' => 'Tanta'],
                ['ar' => 'المحلة الكبرى', 'en' => 'El Mahalla El Kubra'],
                ['ar' => 'زفتى', 'en' => 'Zefta'],
                ['ar' => 'كفر الزيات', 'en' => 'Kafr El Zayat'],
                ['ar' => 'سمنود', 'en' => 'Samanoud'],
                ['ar' => 'قطور', 'en' => 'Qutour'],
                ['ar' => 'بسيون', 'en' => 'Basyoun'],
                ['ar' => 'السنطة', 'en' => 'Al Santa'],
            ],
            'البحيرة' => [
                ['ar' => 'دمنهور', 'en' => 'Damanhur'],
                ['ar' => 'كفر الدوار', 'en' => 'Kafr El Dawwar'],
                ['ar' => 'إيتاي البارود', 'en' => 'Itay El Baroud'],
                ['ar' => 'رشيد', 'en' => 'Rosetta'],
                ['ar' => 'كوم حمادة', 'en' => 'Kom Hamada'],
                ['ar' => 'أبو حمص', 'en' => 'Abu Hummus'],
                ['ar' => 'أبو المطامير', 'en' => 'Abu El Matamir'],
                ['ar' => 'الدلنجات', 'en' => 'Al Delengat'],
                ['ar' => 'المحمودية', 'en' => 'Al Mahmoudiyah'],
                ['ar' => 'إدكو', 'en' => 'Edku'],
                ['ar' => 'حوش عيسى', 'en' => 'Housh Eissa'],
                ['ar' => 'شبراخيت', 'en' => 'Shubrakhit'],
                ['ar' => 'وادي النطرون', 'en' => 'Wadi El Natrun'],
                ['ar' => 'بدر', 'en' => 'Badr - Beheira'],
                ['ar' => 'النوبارية الجديدة', 'en' => 'New Nubariya'],
            ],
            'كفر الشيخ' => [
                ['ar' => 'كفر الشيخ', 'en' => 'Kafr El Sheikh'],
                ['ar' => 'دسوق', 'en' => 'Desouk'],
                ['ar' => 'فوه', 'en' => 'Fouh'],
                ['ar' => 'مطوبس', 'en' => 'Metoubes'],
                ['ar' => 'بلطيم', 'en' => 'Baltim'],
                ['ar' => 'مصيف بلطيم', 'en' => 'Baltim Resort'],
                ['ar' => 'بيلا', 'en' => 'Bila'],
                ['ar' => 'الحامول', 'en' => 'Al Hamool'],
                ['ar' => 'سيدي سالم', 'en' => 'Sidi Salem'],
                ['ar' => 'الرياض', 'en' => 'Al Reyad'],
                ['ar' => 'قلين', 'en' => 'Qallin'],
                ['ar' => 'سيدي غازي', 'en' => 'Sidi Ghazi'],
                ['ar' => 'برج البرلس', 'en' => 'Burg Al Burullus'],
            ],
            'دمياط' => [
                ['ar' => 'دمياط', 'en' => 'Damietta'],
                ['ar' => 'رأس البر', 'en' => 'Ras El Bar'],
                ['ar' => 'دمياط الجديدة', 'en' => 'New Damietta'],
                ['ar' => 'فارسكور', 'en' => 'Faraskur'],
                ['ar' => 'كفر سعد', 'en' => 'Kafr Saad'],
                ['ar' => 'كفر البطيخ', 'en' => 'Kafr El Battikh'],
                ['ar' => 'الزرقا', 'en' => 'Al Zarqa'],
                ['ar' => 'الروضة', 'en' => 'Al Rawda'],
                ['ar' => 'ميت أبو غالب', 'en' => 'Mit Abu Ghaleb'],
                ['ar' => 'السرو', 'en' => 'Al Sarw'],
                ['ar' => 'عزبة البرج', 'en' => 'Ezbet El Borg'],
            ],
            'بورسعيد' => [
                ['ar' => 'حي الشرق', 'en' => 'Al Sharq'],
                ['ar' => 'حي العرب', 'en' => 'Al Arab'],
                ['ar' => 'حي المناخ', 'en' => 'Al Manakh'],
                ['ar' => 'حي الضواحي', 'en' => 'Al Dawahy'],
                ['ar' => 'حي الزهور', 'en' => 'Al Zohour'],
                ['ar' => 'حي غرب', 'en' => 'Gharb District'],
                ['ar' => 'حي الجنوب', 'en' => 'Al Ganoub District'],
                ['ar' => 'بورفؤاد', 'en' => 'Port Fouad'],
                ['ar' => 'شرق بورسعيد', 'en' => 'East Port Said'],
            ],
            'الإسماعيلية' => [
                ['ar' => 'الإسماعيلية', 'en' => 'Ismailia'],
                ['ar' => 'فايد', 'en' => 'Fayed'],
                ['ar' => 'القنطرة غرب', 'en' => 'Qantara West'],
                ['ar' => 'القنطرة شرق', 'en' => 'Qantara East'],
                ['ar' => 'التل الكبير', 'en' => 'El Tal El Kebir'],
                ['ar' => 'القصاصين الجديدة', 'en' => 'Al Qassasin'],
                ['ar' => 'أبو صوير', 'en' => 'Abu Swair'],
            ],
            'السويس' => [
                ['ar' => 'حي السويس', 'en' => 'Suez District'],
                ['ar' => 'حي الأربعين', 'en' => 'Al Arbaeen'],
                ['ar' => 'حي عتاقة', 'en' => 'Attaka'],
                ['ar' => 'حي فيصل', 'en' => 'Faisal District'],
                ['ar' => 'حي الجناين', 'en' => 'Al Ganayen'],
                ['ar' => 'العين السخنة', 'en' => 'Ain Sokhna'],
                ['ar' => 'بورتوفيق', 'en' => 'Port Tewfik'],
            ],
            'الفيوم' => [
                ['ar' => 'الفيوم', 'en' => 'Fayoum'],
                ['ar' => 'الفيوم الجديدة', 'en' => 'New Fayoum'],
                ['ar' => 'سنورس', 'en' => 'Sinnuris'],
                ['ar' => 'إبشواي', 'en' => 'Ibshaway'],
                ['ar' => 'إطسا', 'en' => 'Itsa'],
                ['ar' => 'طامية', 'en' => 'Tamiya'],
                ['ar' => 'يوسف الصديق', 'en' => 'Youssef El Seddik'],
            ],
            'بني سويف' => [
                ['ar' => 'بني سويف', 'en' => 'Beni Suef'],
                ['ar' => 'بني سويف الجديدة', 'en' => 'New Beni Suef'],
                ['ar' => 'الواسطى', 'en' => 'Al Wasta'],
                ['ar' => 'ناصر', 'en' => 'Nasser'],
                ['ar' => 'ببا', 'en' => 'Biba'],
                ['ar' => 'الفشن', 'en' => 'Al Fashn'],
                ['ar' => 'إهناسيا', 'en' => 'Ihnasiya'],
                ['ar' => 'سمسطا', 'en' => 'Sumusta'],
            ],
            'المنيا' => [
                ['ar' => 'المنيا', 'en' => 'Minya'],
                ['ar' => 'المنيا الجديدة', 'en' => 'New Minya'],
                ['ar' => 'ملوي', 'en' => 'Mallawi'],
                ['ar' => 'سمالوط', 'en' => 'Samalut'],
                ['ar' => 'بني مزار', 'en' => 'Beni Mazar'],
                ['ar' => 'مغاغة', 'en' => 'Maghagha'],
                ['ar' => 'أبو قرقاص', 'en' => 'Abu Qurqas'],
                ['ar' => 'مطاي', 'en' => 'Matay'],
                ['ar' => 'العدوة', 'en' => 'Al Idwa'],
                ['ar' => 'دير مواس', 'en' => 'Deir Mawas'],
            ],
            'أسيوط' => [
                ['ar' => 'أسيوط', 'en' => 'Asyut'],
                ['ar' => 'أسيوط الجديدة', 'en' => 'New Asyut'],
                ['ar' => 'مدينة ناصر الجديدة', 'en' => 'New Nasser City'],
                ['ar' => 'ديروط', 'en' => 'Dairut'],
                ['ar' => 'القوصية', 'en' => 'Al Qusiya'],
                ['ar' => 'منفلوط', 'en' => 'Manfalut'],
                ['ar' => 'أبنوب', 'en' => 'Abnoub'],
                ['ar' => 'الفتح', 'en' => 'Al Fateh'],
                ['ar' => 'ساحل سليم', 'en' => 'Sahel Selim'],
                ['ar' => 'البداري', 'en' => 'Al Badari'],
                ['ar' => 'صدفا', 'en' => 'Sedfa'],
                ['ar' => 'الغنايم', 'en' => 'Al Ghanayem'],
            ],
            'سوهاج' => [
                ['ar' => 'سوهاج', 'en' => 'Sohag'],
                ['ar' => 'سوهاج الجديدة', 'en' => 'New Sohag'],
                ['ar' => 'أخميم', 'en' => 'Akhmim'],
                ['ar' => 'أخميم الجديدة', 'en' => 'New Akhmim'],
                ['ar' => 'طهطا', 'en' => 'Tahta'],
                ['ar' => 'جرجا', 'en' => 'Girga'],
                ['ar' => 'المراغة', 'en' => 'Al Maragha'],
                ['ar' => 'المنشأة', 'en' => 'Al Monshaah'],
                ['ar' => 'البلينا', 'en' => 'Al Balyana'],
                ['ar' => 'جهينة', 'en' => 'Guhayna'],
                ['ar' => 'دار السلام', 'en' => 'Dar El Salam'],
                ['ar' => 'ساقلتة', 'en' => 'Saqultah'],
                ['ar' => 'طما', 'en' => 'Tima'],
            ],
            'قنا' => [
                ['ar' => 'قنا', 'en' => 'Qena'],
                ['ar' => 'قنا الجديدة', 'en' => 'New Qena'],
                ['ar' => 'غرب قنا', 'en' => 'West Qena'],
                ['ar' => 'نجع حمادي', 'en' => 'Nag Hammadi'],
                ['ar' => 'قوص', 'en' => 'Qus'],
                ['ar' => 'دشنا', 'en' => 'Dishna'],
                ['ar' => 'أبو تشت', 'en' => 'Abu Tesht'],
                ['ar' => 'فرشوط', 'en' => 'Farshout'],
                ['ar' => 'قفط', 'en' => 'Qift'],
                ['ar' => 'الوقف', 'en' => 'Al Waqf'],
                ['ar' => 'نقادة', 'en' => 'Naqada'],
            ],
            'الأقصر' => [
                ['ar' => 'الأقصر', 'en' => 'Luxor'],
                ['ar' => 'الأقصر الجديدة', 'en' => 'New Luxor'],
                ['ar' => 'طيبة الجديدة', 'en' => 'New Tiba'],
                ['ar' => 'إسنا', 'en' => 'Esna'],
                ['ar' => 'أرمنت', 'en' => 'Armant'],
                ['ar' => 'البياضية', 'en' => 'Al Bayadiya'],
                ['ar' => 'القرنة', 'en' => 'Al Qurna'],
                ['ar' => 'الزينية', 'en' => 'Al Zeiniya'],
                ['ar' => 'الطود', 'en' => 'Al Tod'],
            ],
            'أسوان' => [
                ['ar' => 'أسوان', 'en' => 'Aswan'],
                ['ar' => 'أسوان الجديدة', 'en' => 'New Aswan'],
                ['ar' => 'توشكى الجديدة', 'en' => 'New Toshka'],
                ['ar' => 'كوم أمبو', 'en' => 'Kom Ombo'],
                ['ar' => 'إدفو', 'en' => 'Edfu'],
                ['ar' => 'نصر النوبة', 'en' => 'Nasr Al Nuba'],
                ['ar' => 'دراو', 'en' => 'Daraw'],
                ['ar' => 'أبو سمبل', 'en' => 'Abu Simbel'],
                ['ar' => 'كلابشة', 'en' => 'Kalabsha'],
                ['ar' => 'الرديسية', 'en' => 'Al Radeesiyah'],
                ['ar' => 'البصيلية', 'en' => 'Al Basiliyah'],
                ['ar' => 'السباعية', 'en' => 'Al Sibaiyah'],
            ],
            'البحر الأحمر' => [
                ['ar' => 'الغردقة', 'en' => 'Hurghada'],
                ['ar' => 'الجونة', 'en' => 'El Gouna'],
                ['ar' => 'سفاجا', 'en' => 'Safaga'],
                ['ar' => 'القصير', 'en' => 'Al Quseir'],
                ['ar' => 'مرسى علم', 'en' => 'Marsa Alam'],
                ['ar' => 'رأس غارب', 'en' => 'Ras Gharib'],
                ['ar' => 'شلاتين', 'en' => 'Shalateen'],
                ['ar' => 'حلايب', 'en' => 'Halaib'],
            ],
            'جنوب سيناء' => [
                ['ar' => 'شرم الشيخ', 'en' => 'Sharm El Sheikh'],
                ['ar' => 'دهب', 'en' => 'Dahab'],
                ['ar' => 'نويبع', 'en' => 'Nuweiba'],
                ['ar' => 'طابا', 'en' => 'Taba'],
                ['ar' => 'طور سيناء', 'en' => 'El Tor'],
                ['ar' => 'رأس سدر', 'en' => 'Ras Sudr'],
                ['ar' => 'سانت كاترين', 'en' => 'Saint Catherine'],
                ['ar' => 'أبو رديس', 'en' => 'Abu Rudeis'],
                ['ar' => 'أبو زنيمة', 'en' => 'Abu Zenima'],
            ],
            'شمال سيناء' => [
                ['ar' => 'العريش', 'en' => 'Arish'],
                ['ar' => 'الشيخ زويد', 'en' => 'Sheikh Zuweid'],
                ['ar' => 'رفح', 'en' => 'Rafah'],
                ['ar' => 'رفح الجديدة', 'en' => 'New Rafah'],
                ['ar' => 'بئر العبد', 'en' => 'Bir El Abd'],
                ['ar' => 'الحسنة', 'en' => 'Al Hasana'],
                ['ar' => 'نخل', 'en' => 'Nakhl'],
            ],
            'مطروح' => [
                ['ar' => 'مرسى مطروح', 'en' => 'Marsa Matrouh'],
                ['ar' => 'العلمين', 'en' => 'El Alamein'],
                ['ar' => 'العلمين الجديدة', 'en' => 'New Alamein'],
                ['ar' => 'مارينا', 'en' => 'Marina'],
                ['ar' => 'الحمام', 'en' => 'Al Hamam'],
                ['ar' => 'الضبعة', 'en' => 'Al Dabaa'],
                ['ar' => 'النجيلة', 'en' => 'Al Negila'],
                ['ar' => 'سيدي براني', 'en' => 'Sidi Barrani'],
                ['ar' => 'السلوم', 'en' => 'Al Sallum'],
                ['ar' => 'سيوة', 'en' => 'Siwa'],
            ],
            'الوادي الجديد' => [
                ['ar' => 'الخارجة', 'en' => 'Kharga'],
                ['ar' => 'الداخلة', 'en' => 'Dakhla'],
                ['ar' => 'موط', 'en' => 'Mut'],
                ['ar' => 'الفرافرة', 'en' => 'Farafra'],
                ['ar' => 'باريس', 'en' => 'Baris'],
                ['ar' => 'بلاط', 'en' => 'Balat'],
            ],
        ];

        foreach ($citiesMap as $govName => $cities) {
            $governorate = Governorate::whereTranslation('name', $govName, 'ar')->first();

            if (! $governorate) {
                continue;
            }

            foreach ($cities as $cityData) {
                $existing = City::where('governorate_id', $governorate->id)
                    ->whereTranslation('name', $cityData['ar'], 'ar')
                    ->first();

                if (! $existing) {
                    City::create([
                        'governorate_id' => $governorate->id,
                        'is_active' => true,
                        'ar' => ['name' => $cityData['ar']],
                        'en' => ['name' => $cityData['en']],
                    ]);
                } else {
                    $existing->update([
                        'is_active' => true,
                        'ar' => ['name' => $cityData['ar']],
                        'en' => ['name' => $cityData['en']],
                    ]);
                }
            }
        }
    }
}
